In [1]:
import pandas as pd 
import numpy as np 

In [2]:
df=pd.read_csv('anaemia.csv')

In [3]:
df

Number Sex  %Red Pixel  %Green pixel  %Blue pixel    Hb Anaemic
0         1   M     43.2555       30.8421      25.9025   6.3     Yes
1         2   F     45.6033       28.1900      26.2067  13.5      No
2         3  F      45.0107       28.9677      26.0215  11.7      No
3         4   F     44.5398       28.9899      26.4703  13.5      No
4         5  M      43.2870       30.6972      26.0158  12.4      No
..      ...  ..         ...           ...          ...   ...     ...
99      100  F      49.9999       29.2860      20.7141  14.5     Yes
100     101  M      42.2324       30.6757      27.0919   6.3     Yes
101     102   F     45.6064       31.9084      22.4852  12.7      No
102     103  M      45.2095       29.2769      25.5136  13.4      No
103     104   F     43.5706       29.8094      26.6199  12.2      No

[104 rows x 7 columns]

In [4]:
df=df.drop(['Number'],axis=1)

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
le=LabelEncoder()
df['Anaemic']=le.fit_transform(df['Anaemic'])


In [7]:
df

Sex  %Red Pixel  %Green pixel  %Blue pixel    Hb  Anaemic
0     M     43.2555       30.8421      25.9025   6.3        1
1     F     45.6033       28.1900      26.2067  13.5        0
2    F      45.0107       28.9677      26.0215  11.7        0
3     F     44.5398       28.9899      26.4703  13.5        0
4    M      43.2870       30.6972      26.0158  12.4        0
..   ..         ...           ...          ...   ...      ...
99   F      49.9999       29.2860      20.7141  14.5        1
100  M      42.2324       30.6757      27.0919   6.3        1
101   F     45.6064       31.9084      22.4852  12.7        0
102  M      45.2095       29.2769      25.5136  13.4        0
103   F     43.5706       29.8094      26.6199  12.2        0

[104 rows x 6 columns]

In [8]:
mapping={'M':0,'F':1,}
df['Sex']=df['Sex'].map(mapping)

In [9]:
# print(df[:,1:5])

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
ss=StandardScaler()
df.iloc[:,1:5]=ss.fit_transform(df.iloc[:,1:5])

In [12]:
print(df.iloc[:,0])

0      0.0
1      1.0
2      NaN
3      1.0
4      NaN
      ... 
99     NaN
100    NaN
101    1.0
102    NaN
103    1.0
Name: Sex, Length: 104, dtype: float64


In [13]:
from sklearn.impute import KNNImputer

In [14]:
# df=np.array(df)

In [15]:
imputer=KNNImputer(n_neighbors=5,weights='uniform')
df=imputer.fit_transform(df)

In [16]:
df[:,0]

array([0. , 1. , 0.6, 1. , 0.6, 0. , 1. , 0.8, 1. , 1. , 1. , 1. , 1. ,
       0.8, 0.2, 0. , 1. , 1. , 1. , 1. , 1. , 0.6, 1. , 0. , 0. , 0.6,
       1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.6, 0.4, 0.2, 0. , 1. ,
       0.4, 0.6, 0. , 0. , 0.4, 0. , 0.6, 0. , 0. , 0. , 0.6, 0. , 0. ,
       0. , 0.4, 0. , 0.2, 0. , 0.4, 0.8, 0.4, 0.8, 0.8, 0.2, 1. , 1. ,
       0.6, 1. , 0.8, 1. , 0.8, 0.8, 0.8, 0.4, 0.4, 0.4, 0. , 1. , 1. ,
       1. , 0.6, 0.4, 1. , 1. , 0. , 1. , 1. , 0. , 0.6, 0.4, 0. , 0.6,
       1. , 0. , 0.2, 1. , 0. , 1. , 0. , 0.2, 0.4, 0.8, 1. , 0.6, 1. ])

In [17]:
result=0
for i in df[:,0]:
    if i>=0.5:
        df[result,0]=1.0
    else:
        df[result,0]=0.0
    result+=1

In [18]:
df[:,0]

array([0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
       1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1.,
       1., 1.])

In [19]:
df

array([[ 0.        , -0.85583785,  1.27140733,  0.21881096, -2.33959306,
         1.        ],
       [ 1.        , -0.018152  , -0.44318177,  0.37282795,  0.53943288,
         0.        ],
       [ 1.        , -0.22958936,  0.05960317,  0.27906087, -0.18032361,
         0.        ],
       [ 1.        , -0.39760464,  0.07395553,  0.50628909,  0.53943288,
         0.        ],
       [ 1.        , -0.84459878,  1.17772912,  0.27617495,  0.09958169,
         0.        ],
       [ 0.        , -0.19794155, -0.58896806,  0.74212444,  1.6190676 ,
         0.        ],
       [ 1.        , -0.89501406,  0.83223823,  0.61828304, -1.41990422,
         1.        ],
       [ 1.        , -0.7292466 ,  0.15153582,  0.91614035, -0.74013421,
         0.        ],
       [ 1.        , -0.21831461,  0.1878046 ,  0.16276335,  0.33950052,
         0.        ],
       [ 1.        ,  0.30688923, -0.93568732,  0.29728773, -0.98005303,
         1.        ],
       [ 1.        , -0.10831437,  0.1611687 ,  0.

In [20]:
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

In [21]:
x=df[:,:4]

In [22]:
y=df[:,-1]

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [24]:
param_grid={
    'n_estimators':[100,10,50],
    'learning_rate':[0.1,0.2,0.5],
    'max_depth':[3,5,7],
    'random_state':[42,420,388]
}

In [25]:
grid_search = GridSearchCV(XGBClassifier(), param_grid=param_grid, 
                           scoring='accuracy', cv=3, verbose=1)

In [26]:
grid_search.fit(x_train,y_train)

Fitting 3 folds for each of 81 candidates, totalling 243 fits


GridSearchCV(cv=3,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     feature_types=None, gamma=None,
                                     grow_policy=None, importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None,...
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     multi_strategy=None, n_estimators=None,
                                     n_jobs=None, num_parallel_tree=None,
                                     random_state=None, ...),
             param_grid={'learning_rate': [0.1, 0.2, 0.5],
                         'max_depth': [3, 5, 7], 'n_estimators': [100, 10, 50],
                         'random_state': [42, 420, 388]},
             scoring='accuracy', verbose=1)

In [27]:
grid_search.best_params_

{'learning_rate': 0.2, 'max_depth': 3, 'n_estimators': 10, 'random_state': 42}

In [28]:
algh=XGBClassifier(learning_rate=0.1,max_depth=3,n_estimators=10,random_state=42)

In [29]:
algh.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=10, n_jobs=None,
              num_parallel_tree=None, random_state=42, ...)

In [30]:
algh.score(x_test,y_test)

0.8095238095238095

In [31]:
param_grid={
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf'],
    'gamma': [1, 0.1, 0.01]
}

In [32]:
grid_search2 = GridSearchCV(SVC(), param_grid=param_grid, scoring='accuracy', cv=3)

In [33]:
grid_search2.fit(x_train,y_train)

GridSearchCV(cv=3, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10], 'gamma': [1, 0.1, 0.01],
                         'kernel': ['linear', 'rbf']},
             scoring='accuracy')

In [34]:
grid_search2.best_params_

{'C': 10, 'gamma': 1, 'kernel': 'linear'}

In [35]:
algh2=SVC(C=1,gamma=1,kernel='linear')

In [36]:
algh2.fit(x_train,y_train)

SVC(C=1, gamma=1, kernel='linear')

In [37]:
algh2.score(x_test,y_test)

0.9047619047619048